name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    environment: default
    strategy:
      matrix:
        xcode: ["16.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build package
        run: xcodebuild -scheme intune-ios-sdk-Package -destination generic/platform=iOS
